export enum UserCodeType {
  Account = 'Account',
  AdditionalCost = 'AddlCost',
  AdjustmentReason = 'AdjReasn',
  ARCodes = 'ARCodes',
  Banks = 'Banks',
  Cashflow = 'Cashflow',
  ChangeReason = 'Chngrsn',
  Class = 'Class',
  CustomerType = 'CustType',
  Department = 'Dept',
  Discount = 'Discount',
  FinancialStatement = 'FinStmt',
  FreightClass = 'FrtClass',
  LocationType = 'LocType',
  MStone = 'MStone',
  NMFC = 'NMFC',
  QuoteReason = 'QuoteRsn',
  ScrapReworkCode = 'ScpRwkCd',
  SellUofM = 'SellUofM',
  ShipVia = 'ShipVia',
  TaxCodes = 'TaxCds',
  Terms = 'Terms',
  UofM = 'UofM',
  Warehouse = 'Warehse',
}
