name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - PROD
      - 'dev*' # This will match branches that start with 'dev'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - 
        name: Set current date as env variable
        run: echo "builddate=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
        id: version

    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
    -
        name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

    -
        name: Login to Brown Docker Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REG_URL }}
          username: ${{ secrets.DOCKER_REG_USERNAME }}
          password: ${{ secrets.DOCKER_REG_PASSWORD }}
        
    -
        name: Build and push - PRODUCTION
        if:  startsWith(github.ref, 'refs/heads/PROD')
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          provenance: false
          tags: |
              ${{ vars.DOCKER_REG_URL }}/kaeser-sc2-api:latest
              ${{ vars.DOCKER_REG_URL }}/kaeser-sc2-api:${{ steps.package-version.outputs.current-version}}
              
    -
        name: Build and push - DEV
        if: startsWith(github.ref, 'refs/heads/dev')
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          provenance: false
          tags: |
              ${{ vars.DOCKER_REG_URL }}/kaeser-sc2-api:latest-dev
              ${{ vars.DOCKER_REG_URL }}/kaeser-sc2-api:${{ steps.package-version.outputs.current-version}}-dev
